#!/usr/bin/env bash
# Regenerate the repo-local Hermes Role profiles from the version-controlled
# Role definitions.
#
# Hermes does not read roles/<role>/SOUL.md directly. At runtime it reads
# HERMES_HOME/profiles/<role>/SOUL.md, and scripts/hermes-serve.sh sets
# HERMES_HOME to this repository's hermes-home/. This script is the explicit
# bridge between the committed Role source files and the generated Hermes
# runtime profile files.
#
# Source of truth:
#   roles/sales/SOUL.md
#   roles/admin/SOUL.md
#   roles/MODELS.md
#   .env                 model/provider choices for this local deployment
#
# Generated runtime files:
#   hermes-home/config.yaml
#   hermes-home/profiles/sales/config.yaml
#   hermes-home/profiles/sales/SOUL.md
#   hermes-home/profiles/admin/config.yaml
#   hermes-home/profiles/admin/SOUL.md
#
# Do not edit hermes-home/profiles/* by hand: re-run this script after changing
# roles/*/SOUL.md or the model variables in .env.
#
#   ./scripts/apply-models.sh          # then restart hermes to pick it up
#
# See roles/MODELS.md for which model suits which Role and why.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
elif [ -z "${MODEL_PROVIDER:-}" ] || [ -z "${SALES_MODEL:-}" ] || [ -z "${ADMIN_MODEL:-}" ]; then
  echo "error: .env is missing and model variables are not present in the environment." >&2
  echo "Run scripts/bootstrap.sh locally, or provide MODEL_PROVIDER, SALES_MODEL, and ADMIN_MODEL in the container environment." >&2
  exit 1
fi

# Model choice is explicit configuration, not hidden script behavior.
# .env.example must list these variables, and each real .env must carry them.
# If an older .env is missing them, fail with a direct message instead of
# silently choosing a model the operator cannot see in their local config.
: "${MODEL_PROVIDER:?MODEL_PROVIDER is missing in .env. Copy the model selection block from .env.example.}"
: "${SALES_MODEL:?SALES_MODEL is missing in .env. Copy the model selection block from .env.example.}"
: "${ADMIN_MODEL:?ADMIN_MODEL is missing in .env. Copy the model selection block from .env.example.}"
PROVIDER="$MODEL_PROVIDER"
SALES="$SALES_MODEL"
ADMIN="$ADMIN_MODEL"

write_profile() {
  local role="$1" model="$2" dir="hermes-home/profiles/$1"
  mkdir -p "$dir"
  # Each Role is a separate Hermes profile so its system prompt and tool surface
  # stay stable for prompt caching. The config is generated from .env so model
  # selection changes in one place without editing generated runtime state.
  cat > "$dir/config.yaml" <<YAML
# GENERATED by scripts/apply-models.sh — edit .env, not this file.
# Model choice per Role: see roles/MODELS.md.
model:
  default: "$model"
  provider: "$PROVIDER"

# Hermes core is unmodified; this only enables the standalone product plugin.
plugins:
  enabled:
    - realestate
YAML
  # Copy, rather than symlink, so the runtime profile is self-contained if the
  # service is later packaged onto a server with hermes-home as durable state.
  cp "roles/$role/SOUL.md" "$dir/SOUL.md"
  printf '  %-6s %s\n' "$role" "$model"
}

# The top-level HERMES_HOME profile is the process launch profile used by
# `hermes serve`. Conversation work uses the sales/admin profiles, but the
# server itself still needs a valid default model and the realestate plugin.
cat > hermes-home/config.yaml <<YAML
# GENERATED by scripts/apply-models.sh — edit .env, not this file.
model:
  default: "$ADMIN"
  provider: "$PROVIDER"

plugins:
  enabled:
    - realestate
YAML

echo "provider: $PROVIDER"
write_profile sales "$SALES"
write_profile admin "$ADMIN"
echo
echo "Restart Hermes to apply:  pkill -f 'hermes serve' && ./scripts/hermes-serve.sh &"
